[project]
name = "neuroclip"
version = "0.1.0"
description = "AI-powered clipboard manager with custom prompts"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "googletrans>=4.0.2",
    "nuitka[onefile]>=4.0.8",
    "openai>=2.8.1",
    "pyautogui>=0.9.54",
    "pyinstaller>=6.16.0",
    "pynput>=1.8.1",
    "pyside6>=6.10.0",
    "qasync>=0.28.0",
    "qt-material>=2.17",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.20",
]

[project.scripts]
neuroclip = "main:main"
