[project]
name = "clipboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "googletrans>=4.0.2",
    "openai>=2.8.1",
    "pyautogui>=0.9.54",
    "pyinstaller>=6.16.0",
    "pynput>=1.8.1",
    "pyperclip>=1.11.0",
    "pyside6>=6.10.0",
    "qasync>=0.28.0",
    "qt-material>=2.17",
]
